### ISSUE TITLE
how to utilize templates

### ISSUE THREAD

**Issue by ibarbe33** [ibarbe33/clean-home#2]
I wrote to the Professor and asked if there is a way to write on this document for the waterfall template https://docs.google.com/document/d/1vJ2aC8ama0rXA3kQmWjkXGGqpQTQpPqEbSHI5gAeKq8/edit

**Comment by Orthogonal-Research-Lab** [comment]
This is a good issue. See my response in the Googe Doc: "You can add a text box in Google Drive via: Insert → Drawing → Add Textbox. Or on the template, just select the textbox and type. You can write inside the box, but the default boxes are small, so you would need to make each box bigger. Just don’t overdo it.".

**Comment by ibarbe33** [comment]
The professor told me to download and open in google drive.
